# Generated by Django 4.1.3 on 2022-11-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paisajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paisaje', models.CharField(max_length=150)),
                ('lugar_historico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=150)),
                ('continente', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=900)),
            ],
        ),
    ]
