# Generated by Django 4.1.3 on 2022-11-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDestinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=150)),
                ('continente', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=900)),
                ('paisaje', models.CharField(max_length=150)),
                ('cantidad_poblacion', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Paisajes',
        ),
        migrations.DeleteModel(
            name='Paises',
        ),
    ]
