# Generated by Django 4.1.3 on 2022-12-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDestinos', '0002_destinos_delete_paisajes_delete_paises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinos',
            old_name='cantidad_poblacion',
            new_name='poblacion',
        ),
    ]
