# Generated by Django 4.1.3 on 2022-12-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDestinos', '0003_rename_cantidad_poblacion_destinos_poblacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinos',
            old_name='nombre_pais',
            new_name='nombre',
        ),
    ]
