# Generated by Django 4.1.3 on 2022-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDestinos', '0004_rename_nombre_pais_destinos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinos',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='subidas'),
        ),
    ]
